development:
  adapter: postgresql
  encoding: unicode
  database: books_development
  pool: 5
  username: tim
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: books_development
  pool: 5
  username: tim
  password:
